# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 286b66d71e0d02725fa9bbb8ed1d260173fff500900922d826b38b4ff568f174da60abb72822184f15b1f5da9b460fbd9b46bf6eb47f85f7516e60c3b36e26f1

test:
  secret_key_base: 1c7f3dd68cee966eee48e403542bf1dc23b813a5530b3aec9d7d6e9db5088c026c6e3deb81f6611ea87b57b3ae3ed4b345d62f9e9c0065843bf2f248a1605372

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
